<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-CABlazorApp-b9cf2049-94de-44fc-8e80-68b1d9571714</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Zip" Version="23.2.0" />
    <PackageReference Include="BlazorDownloadFile" Version="2.4.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="7.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.5" />
    <PackageReference Include="Mono.Cecil" Version="0.11.4" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="7.0.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\uploads\dortwess@gmail.com\files\soubor.docx" />
    <_ContentIncludedByDefault Remove="wwwroot\uploads\dortwess@gmail.com\testCertificate.pfx" />
    <_ContentIncludedByDefault Remove="wwwroot\uploads\ahoj@example.com\certifikat.pfx" />
    <_ContentIncludedByDefault Remove="wwwroot\uploads\ahoj@example.com\files\file.docx" />
    <_ContentIncludedByDefault Remove="wwwroot\uploads\files\document.docx" />
    <_ContentIncludedByDefault Remove="wwwroot\uploads\files\Heslo.docx" />
    <_ContentIncludedByDefault Remove="wwwroot\files\file.txt" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\ahoj@ahoj.com\files\file.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Archive" />
    <Folder Include="Archive\example@example.com\certificates" />
    <Folder Include="Archive\example@example.com\files" />
    <Folder Include="Archive\example@example.com\temp" />
    <Folder Include="Archive\test@test.com\files" />
    <Folder Include="Archive\test@test.com\temp" />
    <Folder Include="Areas\Identity\Pages\Shared" />
  </ItemGroup>

</Project>
